"""empty message

Revision ID: 13e9dc2e75d2
Revises: 9dc17551e490
Create Date: 2021-08-26 18:34:36.675947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e9dc2e75d2'
down_revision = '9dc17551e490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('viewer', sa.Column('organization', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('viewer', 'organization')
    # ### end Alembic commands ###
