"""empty message

Revision ID: 1588bb81011c
Revises: e5bc6b018432
Create Date: 2021-08-13 01:00:43.074509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1588bb81011c'
down_revision = 'e5bc6b018432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'end_date')
    op.drop_column('project', 'start_date')
    # ### end Alembic commands ###
