"""empty message

Revision ID: 3f411b03fd92
Revises: fdb677bbd768
Create Date: 2021-08-13 15:02:16.765350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f411b03fd92'
down_revision = 'fdb677bbd768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('start', sa.Date(), nullable=True))
    op.add_column('project', sa.Column('end', sa.Date(), nullable=True))
    op.drop_column('project', 'start_date')
    op.drop_column('project', 'end_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('end_date', sa.DATE(), nullable=True))
    op.add_column('project', sa.Column('start_date', sa.DATE(), nullable=True))
    op.drop_column('project', 'end')
    op.drop_column('project', 'start')
    # ### end Alembic commands ###
