"""empty message

Revision ID: 7bcd0657fb93
Revises: 
Create Date: 2021-08-20 11:25:11.518884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bcd0657fb93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grade', sa.Column('parameter_5', sa.Integer(), nullable=True))
    op.add_column('grade', sa.Column('parameter_6', sa.Integer(), nullable=True))
    op.add_column('grade', sa.Column('parameter_7', sa.Integer(), nullable=True))
    op.add_column('grade', sa.Column('parameter_8', sa.Integer(), nullable=True))
    op.add_column('grade', sa.Column('parameter_9', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('sum_grade_5', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('sum_grade_6', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('sum_grade_7', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('sum_grade_8', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('sum_grade_9', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'sum_grade_9')
    op.drop_column('user', 'sum_grade_8')
    op.drop_column('user', 'sum_grade_7')
    op.drop_column('user', 'sum_grade_6')
    op.drop_column('user', 'sum_grade_5')
    op.drop_column('grade', 'parameter_9')
    op.drop_column('grade', 'parameter_8')
    op.drop_column('grade', 'parameter_7')
    op.drop_column('grade', 'parameter_6')
    op.drop_column('grade', 'parameter_5')
    # ### end Alembic commands ###
