"""empty message

Revision ID: 9dc17551e490
Revises: 
Create Date: 2021-08-23 15:16:08.968807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc17551e490'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_expert_email', table_name='expert')
    op.create_index(op.f('ix_expert_email'), 'expert', ['email'], unique=False)
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_expert_email'), table_name='expert')
    op.create_index('ix_expert_email', 'expert', ['email'], unique=False)
    # ### end Alembic commands ###
