"""expert table

Revision ID: b31ac2ef0590
Revises: 
Create Date: 2021-07-25 13:47:58.268262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31ac2ef0590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grade', 'timestamp')
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.DATE(), nullable=True))
    op.add_column('grade', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
