"""empty message

Revision ID: c7d46b0fae29
Revises: 7bcd0657fb93
Create Date: 2021-08-20 13:31:38.122359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d46b0fae29'
down_revision = '7bcd0657fb93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('phone_number', sa.String(length=16), nullable=True))
    op.add_column('viewer', sa.Column('phone_number', sa.String(length=16), nullable=True))
    op.add_column('waiting_user', sa.Column('phone_number', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiting_user', 'phone_number')
    op.drop_column('viewer', 'phone_number')
    op.drop_column('admin', 'phone_number')
    # ### end Alembic commands ###
