"""empty message

Revision ID: f70cd821a915
Revises: 13f61ff06e11
Create Date: 2021-10-24 15:34:40.062516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f70cd821a915'
down_revision = '13f61ff06e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expert', sa.Column('photo', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expert', 'photo')
    # ### end Alembic commands ###
