"""empty message

Revision ID: fa2688284a6f
Revises: d75239c34618
Create Date: 2021-08-26 18:43:10.483346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2688284a6f'
down_revision = 'd75239c34618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiting_user', sa.Column('organization', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiting_user', 'organization')
    # ### end Alembic commands ###
